site_name: Health Services Platform (HSP) Marketplace

theme:
  name: 'material'
  logo: 'images/old-hspc-logo.png'
  favicon: 'images/old-hspc-logo.png'
  palette:
    primary: 'grey'
    accent: 'red'
    
   

nav:
- Home: 'index.md'
- Ballots:
  - 2 STU1: 
    - Health Services Platform Marketplace : 'ballots/HL7_HSP_R2_STU1_2019SEP/index.md'
    - License Information : 'ballots/HL7_HSP_R2_STU1_2019SEP/license.md'
    - Executive Summary : 'ballots/HL7_HSP_R2_STU1_2019SEP/executive_summary.md'
    - Core Concepts :  'ballots/HL7_HSP_R2_STU1_2019SEP/core_concepts.md'      
    - Digital Rights Management :  'ballots/HL7_HSP_R2_STU1_2019SEP/digital_rights_management.md'      
    - Functional Infrastructure Model : 'ballots/HL7_HSP_R2_STU1_2019SEP/functional_infrastructure_model.md'  
    - Reference implementation : 'ballots/HL7_HSP_R2_STU1_2019SEP/reference_implementation.md'
    - Standards : 'ballots/HL7_HSP_R2_STU1_2019SEP/reference_standards.md'    
    - Model Quick Reference : 'ballots/HL7_HSP_R2_STU1_2019SEP/model_quick_reference.md'        
    - API : 'ballots/HL7_HSP_R2_STU1_2019SEP/api.md'
  - 1.0 Informative: 'ballots/HL7_V3_HSP_R1_I1_2019JAN/index.md'

copyright: © 2019 HL7 & HSPC <p></p>  <img  align="left" alt="HL7 International" src="/images/hl7-logo.png" />  <img  align="right" alt="HSPC" src="/images/old-hspc-logo.png" />    
