site_name: Health Services Platform (HSP) Marketplace

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  favicon: 'images/favicon.png'

nav:
- Health Services Platform (HSP) Marketplace : 'index.md'
- License Information : 'license.md'
- Executive Summary : 'ExecutiveSummary.md'
- Concepts :  'CoreConcepts.md'      
- Digital Rights Management :  'DigitalRightsManagement.md'      
- Functional Infrastructure Model : 'FunctionalInfrastructureModel.md'  
- Reference implementation : 'referenceimplementation.md'
- Standards : 'referenceStandards.md'    
- Model Quick Reference : 'modelquickreference.md'        
- API : 'api.md'
