site_name: Health Services Platform (HSP) Marketplace

theme:
  name: 'material'
  logo: 'images/old-hspc-logo.png'
  favicon: 'images/old-hspc-logo.png'
  palette:
    primary: 'grey'
    accent: 'red'
    
   

nav:
- Home: 'index.md'
- Ballots:
  - 1.0: 'ballots/HL7_V3_HSP_R1_I1_2019JAN/index.md'
  - 1.1: 
    - Health Services Platform Marketplace : 'ballots/HL7_V3_HSP_R2_2019SEP/index.md'
    - License Information : 'ballots/HL7_V3_HSP_R2_2019SEP/license.md'
    - Executive Summary : 'ballots/HL7_V3_HSP_R2_2019SEP/ExecutiveSummary.md'
    - Concepts :  'ballots/HL7_V3_HSP_R2_2019SEP/CoreConcepts.md'      
    - Digital Rights Management :  'ballots/HL7_V3_HSP_R2_2019SEP/DigitalRightsManagement.md'      
    - Functional Infrastructure Model : 'ballots/HL7_V3_HSP_R2_2019SEP/FunctionalInfrastructureModel.md'  
    - Reference implementation : 'ballots/HL7_V3_HSP_R2_2019SEP/referenceimplementation.md'
    - Standards : 'ballots/HL7_V3_HSP_R2_2019SEP/referenceStandards.md'    
    - Model Quick Reference : 'ballots/HL7_V3_HSP_R2_2019SEP/modelquickreference.md'        
    - API : 'ballots/HL7_V3_HSP_R2_2019SEP/api.md'

copyright: © 2019 HL7 & HSPC <p></p>  <img  align="left" alt="HL7 International" src="/images/hl7-logo.png" />  <img  align="right" alt="HSPC" src="/images/old-hspc-logo.png" />    
